
import pandas as pd
import pandas_ta as ta

def check_bb_columns():
    df = pd.DataFrame({'close': [i for i in range(200)]})
    bb_length = 100
    bb_std_dev = 2.0
    
    try:
        bb = ta.bbands(df["close"], length=bb_length, std=bb_std_dev)
        print("Columns generated by pandas_ta.bbands:")
        print(bb.columns.tolist())
        
        expected_col = f"BBB_{bb_length}_{bb_std_dev}"
        print(f"\nExpected column: {expected_col}")
        
        if expected_col in bb.columns:
            print("Status: Found expected column.")
        else:
            print("Status: Expected column NOT found.")
            
    except Exception as e:
        print(f"Error running pandas_ta.bbands: {e}")

if __name__ == "__main__":
    check_bb_columns()
